# Generated by Django 5.2.7 on 2025-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sdf',
            },
        ),
    ]
