# Generated by Django 5.2.7 on 2025-11-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-publicTime']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publicTime']},
        ),
    ]
