# Generated by Django 5.2.7 on 2025-11-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0002_ww'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WW',
        ),
    ]
