# Generated by Django 5.2.7 on 2025-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0003_delete_ww'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_table',
            name='stared_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
