# Generated by Django 5.2.7 on 2025-11-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0004_alter_star_table_stared_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
