# Generated by Django 5.2.7 on 2025-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0005_blogpost_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_table',
            name='blog_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='star_table',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
